spring:
  application:
    name: transferprojekt

  datasource:
    url: jdbc:postgresql://localhost:5432/transferprojekt
    username: transferprojekt
    password: transferprojekt

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
